version: '3.8'

services:
  makna-ai-fastapi:
    build: .
    volumes:
      - .:/app

    env_file:
      - .env

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.makna-ai-fastapi.rule=Host(`makna.ai.vncnttan.my.id`)"
      - "traefik.http.routers.makna-ai-fastapi.entrypoints=websecure"
      - "traefik.http.routers.makna-ai-fastapi.tls.certresolver=app1"
      - "traefik.http.services.makna-ai-fastapi.loadbalancer.server.port=7860"
    
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
